GET http://localhost:3000

###

GET http://localhost:3000/books

###
GET http://localhost:3000/books/83624869839864398
###

POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Super livre",
  "description": "Description du livre",
  "image": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/contemporary-fiction-night-time-book-cover-design-template-1be47835c3058eb42211574e0c4ed8bf_screen.jpg?ts=1594616847",
  "author": "Angelina Aludo",
  "stars": 5,
  "price": 10.2
}

###

PATCH http://localhost:3000/books/609a8b38ecaf8b8aa776d70a
Content-Type: application/json

{
  "title": "Un nouveau titre 2 !",
  "description": "ça marche ??"
}

###
DELETE http://localhost:3000/books/609a87137fdc501fd1b95669
