GET http://localhost:3000

###

GET http://localhost:3000/books

###

POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Super livre",
  "description": "Description du livre",
  "image": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/contemporary-fiction-night-time-book-cover-design-template-1be47835c3058eb42211574e0c4ed8bf_screen.jpg?ts=1594616847",
  "price": 9.7,
  "author": "Angelina Aludo",
  "stars": 5
}